Repository leaphigh/WWL, pull requests merged in 2021-01, with the labels that each got.

#1 Set goal of coco's 1Q and 1st
  README.md
  coco/README.md
Labels: set goal of week

#2 Set goal of 1q 1st week
  altera520/README.md
Labels: set goal of week

#3 Set goal of jaehong2 1Q 1st week
  README.md
  jaehong2/README.md
Labels: set goal of week

#4 Add coco's 1st contents and templates
  coco/TEMPLATES/[algorithm] 2021-nst TEMPLATE/2021-nst.md
  coco/TEMPLATES/[translation] 2021-nq TEMPLATE.md
  coco/algorithm/2021-1st/2021-1st.md
  coco/translation/2021-1q.md
Labels: weekly contents

#7 Set goal of 2st
  coco/README.md
  coco/TEMPLATES/2021-nst.md
  coco/algorithm/2021-01st.md
  coco/algorithm/2021-02st.md
Labels: set goal of week

#9 Merge altera520 to main branch
  altera520/README.md
Labels: set goal of week

#11 Add coco's 2st contents and Update TEMPLATES
  coco/README.md
  coco/TEMPLATES/2021-nst.md
  coco/TEMPLATES/[algorithm] 2021-nst.md
  coco/TEMPLATES/[translation] 2021-nq.md
  coco/algorithm/2021-02st.md
  coco/translation/2021-1q.md
Labels: weekly contents

#13 Add result of 1q 2nd weeks and Add .gitignore
  .gitignore
  jaehong2/README.md
Labels: weekly contents

#16 Add goal of 1q 3rd
  altera520/README.md
Labels: set goal of week

#18 Add result of 1q 3st and Set goal result of 1q 4st
  coco/README.md
  coco/algorithm/2021-03st.md
  coco/algorithm/2021-04st.md
Labels: set goal of week, weekly contents

#21 Add result of 1q 4st
  README.md
  coco/README.md
  coco/algorithm/2021-04st.md
  coco/translation/2021-1q.md
Labels: weekly contents
